/**
 * CATEGORIES
 * @type {string}
 */
export const CATEGORY_FETCH_READ = "CATEGORY_FETCH_READ";
export const CATEGORY_FETCH_READ_SUCCESS = "CATEGORY_FETCH_READ_SUCCESS";
export const CATEGORY_FETCH_READ_FAILED = "CATEGORY_FETCH_READ_FAILED";

export const CATEGORY_CREATE_INIT = "CATEGORY_CREATE_INIT";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAILED = "CATEGORY_CREATE_FAILED";

export const CATEGORY_UPDATE_INIT = "CATEGORY_UPDATE_INIT";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAILED = "CATEGORY_UPDATE_FAILED";

export const CATEGORY_DELETE_INIT = "CATEGORY_DELETE_INIT";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAILED = "CATEGORY_DELETE_FAILED";

export const CATEGORY_GET_ALL_INIT = "CATEGORY_GET_ALL_INIT";
export const CATEGORY_GET_ALL_SUCCESS = "CATEGORY_GET_ALL_SUCCESS";
export const CATEGORY_GET_ALL_FAILED = "CATEGORY_GET_ALL_FAILED";

/***
 * MESSAGES
 * @type {string}
 */
export const MESSAGES_FETCH_READ = "MESSAGES_FETCH_READ";
export const MESSAGES_FETCH_READ_SUCCESS = "MESSAGES_FETCH_READ_SUCCESS";
export const MESSAGES_FETCH_READ_FAILED = "MESSAGES_FETCH_READ_FAILED";

export const MESSAGES_CREATE_INIT = "MESSAGES_CREATE_INIT";
export const MESSAGES_CREATE_SUCCESS = "MESSAGES_CREATE_SUCCESS";
export const MESSAGES_CREATE_FAILED = "MESSAGES_CREATE_FAILED";

export const MESSAGES_UPDATE_INIT = "MESSAGES_UPDATE_INIT";
export const MESSAGES_UPDATE_SUCCESS = "MESSAGES_UPDATE_SUCCESS";
export const MESSAGES_UPDATE_FAILED = "MESSAGES_UPDATE_FAILED";

export const MESSAGES_DELETE_INIT = "MESSAGES_DELETE_INIT";
export const MESSAGES_DELETE_SUCCESS = "MESSAGES_DELETE_SUCCESS";
export const MESSAGES_DELETE_FAILED = "MESSAGES_DELETE_FAILED";
