/**
 * CATEGORIES
 * @type {string}
 */
export const CATEGORY_FETCH_READ = "CATEGORY_FETCH_READ";
export const CATEGORY_FETCH_READ_SUCCESS = "CATEGORY_FETCH_READ_SUCCESS";
export const CATEGORY_FETCH_READ_FAILED = "CATEGORY_FETCH_READ_FAILED";

export const CATEGORY_CREATE_INIT = "CATEGORY_CREATE_INIT";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAILED = "CATEGORY_CREATE_FAILED";

export const CATEGORY_UPDATE_INIT = "CATEGORY_UPDATE_INIT";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAILED = "CATEGORY_UPDATE_FAILED";

export const CATEGORY_DELETE_INIT = "CATEGORY_DELETE_INIT";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAILED = "CATEGORY_DELETE_FAILED";
