export const CATEGORY_FETCH_READ = "CATEGORY_FETCH_READ";
export const CATEGORY_FETCH_READ_SUCCESS = "CATEGORY_FETCH_READ_SUCCESS";
export const CATEGORY_FETCH_READ_FAILED = "CATEGORY_FETCH_READ_FAILED";